### ISSUE TITLE
pusher app key being used - maybe hitting limits?

### ISSUE THREAD

**Issue by NathanWalker** [pusher-community/realtime-twitter-search-angular2#2]
I noticed that while running the code locally with the app key found in the src, no tweets would ever come in. May be hitting limits on that demo app key? 

Not sure.

**Comment by jackfranklin** [comment]
Hey,

I just checked and it's working now, although the API server was being a bit slow. The demo's working for me although it can be a bit temperamental. I'm working on improving the reliability of the API at the moment.

**Comment by NathanWalker** [comment]
N/p thanks I was able to get it to work eventually :) Good stuff.
